cart/urls.py
from django.urls import path
from . import views
app_name='cart'
urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('shop/',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),

]

ecomerceproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls'))
]
if settings.DEBUG:
     urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
     urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
     

search_app/urls.py
from django.urls import path
from . import views

app_name='search_app'
urlpatterns=[
    path('serach/',views.SearchResult,name='SearchResult'),
]

shop/urls.py

from django.urls import path
from . import views
app_name='shop'
urlpatterns = [

    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>',views.proDetail,name='prodCatdetail'),

]

cart/models.py
from django.db import models
from shop.models import Product
# Create your models here.

class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']

    def __str__(self):
        return '{}' .format(self.cart_id)

class Cartitem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CartItem'
    def sub_total(self):
    
        return (self.product.price * self.quantity) + self.product.shippingprice
        

    def __str__(self):
        return '{}'.format(self.product)

shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField( blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='catergories'

    def get_url(self):
        return reverse('shop:products_by_category',args=[self.slug])

    def __str__(self):
        return '{}'. format(self.name)

class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    shippingprice=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
 
    def get_url(self):
        return reverse('shop:prodCatdetail',args=[self.category.slug,self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)





cart/views.py
from django.shortcuts import render,redirect,get_object_or_404
from shop.models import Product
from .models import Cart,Cartitem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.

def cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=cart_id(request))

    except Cart.DoesNotExist:
        cart=Cart.objects.create(
            cart_id=cart_id(request)
        )
        cart.save()

    try:
        cart_items=Cartitem.objects.get(product=product,cart=cart)
        if cart_items.quantity < cart_items.product.stock:
            cart_items.quantity += 1
            cart_items.save()
    except Cartitem.DoesNotExist:
        cart_item=Cartitem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()

    return redirect('cart:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None,stotal=0,ttotal=0):
    try:
        cart=Cart.objects.get(cart_id=cart_id(request))
        cart_items=Cartitem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity )
            counter += cart_item.quantity
            stotal +=(cart_item.product.shippingprice)
            ttotal = (total+stotal)
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter,stotal=stotal,ttotal=ttotal))


def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_items=Cartitem.objects.get(product=product,cart=cart)
    if cart_items.quantity >1:
        cart_items.quantity -=1
        cart_items.save()

    else:
        cart_items.delete()
    return redirect('cart:cart_detail')

def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_items=Cartitem.objects.get(product=product,cart=cart)
    cart_items.delete()
    return redirect('cart:cart_detail')
    # return redirect(reverse('cart:cart_detail'))

search_app/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q
# Create your views here.


def SearchResult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request,'search.html',{'query':query,'products':products})

shop/views.py

from django.shortcuts import render, get_object_or_404
from . models import Category,Product
from  django.core.paginator import Paginator,EmptyPage,InvalidPage


# Create your views here.
def allProdCat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)


    return render(request,"category.html",{'category':c_page,'products':products})

def proDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e

    return render(request,'product.html',{'product':product})


templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital@1&display=swap" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet"> 

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">\
    /
    <!-- Libraries Stylesheet -->
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
{% include 'header.html' %}
{% include 'nav.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
  <script src="{% static 'js/popper.min.js' %}" ></script>
  <script src="{% static 'js/bootstrap.min.js' %}" ></script>

</body>
</html>

templates/cart.html

{% extends 'base.html' %}
{% load static %}
{% block content%}

<section class="h-100 gradient-custom">
    <div class="container py-5">
      <div class="row d-flex justify-content-center my-4">
        <div class="col-md-8">
          <div class="card mb-4">
            <div class="card-header py-3">
              <h5 class="mb-0">Cart - {{item_count}} items</h5>
            </div>
            <div class="card-body">
              {% if not cart_items %}
              <div>
                  <div class="text-center">
                      <br>
                      <h1 class="text-center my_title">
                          Your Shoppin cart is Empty
                      </h1>
                      <br>
                      <p class="text-center">
                          Please click <a class="btn btn-info" href={% url 'shop:allProdCat' %}>Here</a> to continue shopping.
                      </p>

                  </div>
              </div>
              {% else %}
              <!-- Single item -->
              {% for cart_item in cart_items %}
              {% if cart_item.quantity < cart_item.product.stock %}
              <div class="row">
                <div class="col-lg-3 col-md-12 mb-4 mb-lg-0">
                  <!-- Image -->
                  <div class="bg-image hover-overlay hover-zoom ripple rounded" data-mdb-ripple-color="light">
                    <a href="{{ cart_item.product.get_url }}"><img height="150px;" src="{{cart_item.product.image.url}}" alt="" class="float-left rounded custom_image"
                      class="w-100" alt="Blue Jeans Jacket" /></a>
                    <a href="#!">
                      <div class="mask" style="background-color: rgba(251, 251, 251, 0.2)"></div>
                    </a>
                  </div>
                  <!-- Image -->
                </div>
  
                <div class="col-lg-5 col-md-6 mb-4 mb-lg-0">
                  <!-- Data -->
                  <p><strong>{{cart_item.product.name}}</strong></p>
                  <p> SKU: {{cart_item.product.id}}</p>
                  <p> price: $ {{cart_item.product.price}}</p>
                  <p>shipping fee:  ${{cart_item.product.shippingprice}}</p>
                  
                 <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a">
                  <button type="button" class="btn btn-danger btn-sm mb-2" data-mdb-toggle="tooltip"
                    title="Move to the wish list">
                    <img src="{% static 'img/bin.png' %}" style="width: 15px;">
                  </button></a>
                  <!-- Data -->
                </div>
  
                <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
                  <!-- Quantity -->
                  
                  <div class="d-flex mb-4" style="max-width: 300px">
                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}"class="custom_a"><button class="btn btn-primary px-3 ms-2"><img src="{% static 'img/minus.png' %}"style="width: 15px;"></button></a>
                  
                     <div class="form-outline">
                    
                      <button type="button" class="btn btn-light">QTY : {{cart_item.quantity}}</button>
                    </div>
                      <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><button class="btn btn-primary px-3 ms-2"><img src="{% static 'img/plus.png' %}" style="width: 15px;"></button></a>
                    </div>
                  <!-- Quantity -->
  
                  <!-- Price -->
                  <p class="text-start text-md-center">
                    <strong> $ {{cart_item.sub_total}}</strong>
                  </p>
                  
                  <!-- Price -->
                </div>
              </div>
              <!-- Single item -->
             
              {% else %}
           
              <div class="row">
                <div class="col-lg-3 col-md-12 mb-4 mb-lg-0">
                  <!-- Image -->
                  <div class="bg-image hover-overlay hover-zoom ripple rounded" data-mdb-ripple-color="light">
                    <a href="{{ cart_item.product.get_url }}"><img height="150px;" src="{{cart_item.product.image.url}}" alt="" class="float-left rounded custom_image"
                      class="w-100" alt="Blue Jeans Jacket" /></a>
                    <a href="#!">
                      <div class="mask" style="background-color: rgba(251, 251, 251, 0.2)"></div>
                    </a>
                  </div>
                  <!-- Image -->
                </div>
  
                <div class="col-lg-5 col-md-6 mb-4 mb-lg-0">
                  <!-- Data -->
                  <p><strong>{{cart_item.product.name}}</strong></p>
                  <p> SKU: {{cart_item.product.id}}</p>
                  <p> price: $ {{cart_item.product.price}}</p>
                  <p>shipping fee:  ${{cart_item.product.shippingprice}}</p>
                  
                 <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a">
                  <button type="button" class="btn btn-danger btn-sm mb-2" data-mdb-toggle="tooltip"
                    title="Move to the wish list">
                    <img src="{% static 'img/bin.png' %}" style="width: 15px;">
                  </button></a>
                  <!-- Data -->
                </div>
  
                <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
                  <!-- Quantity -->
                  
                  <div class="d-flex mb-4" style="max-width: 300px">
                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}"class="custom_a"><button class="btn btn-primary px-3 ms-2"><img src="{% static 'img/minus.png' %}"style="width: 15px;"></button></a>
                  
                     <div class="form-outline">
                    
                      <button type="button" class="btn btn-light">QTY : {{cart_item.quantity}}</button>
                    </div>
                     
                    </div>
                  <!-- Quantity -->
  
                  <!-- Price -->
                  <p class="text-start text-md-center">
                    <strong> $ {{cart_item.sub_total}}</strong>
                  </p>
                  
                  <!-- Price -->
                </div>
              </div>
             
              {% endif %}
              {% endfor %}
              {% endif %}
             
            </div>
          </div>
          <div class="card mb-4">
            <div class="card-body">
              <p><strong>Expected shipping delivery</strong></p>
              <p class="mb-0">12.10.2020 - 14.10.2020</p>
            </div>
          </div>
          <div class="card mb-4 mb-lg-0">
            <div class="card-body">
              <p><strong>We accept</strong></p>
              <img class="me-2" width="45px"
                src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/visa.svg"
                alt="Visa" />
              <img class="me-2" width="45px"
                src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/amex.svg"
                alt="American Express" />
              <img class="me-2" width="45px"
                src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/mastercard.svg"
                alt="Mastercard" />
              <img class="me-2" width="45px"
                src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce/includes/gateways/paypal/assets/images/paypal.webp"
                alt="PayPal acceptance mark" />
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4">
            <div class="card-header py-3">
              <h5 class="mb-0">Summary</h5>
            </div>
            <div class="card-body">
              <ul class="list-group list-group-flush">
                <li
                  class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
                  Products
                  <span>$ {{ total }}</span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                  Shipping
                  <span>$ {{ stotal }}</span>
                </li>
                <li
                  class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                  <div>
                    <strong>Total amount</strong>
                    <strong>
                      <p class="mb-0">(including VAT)</p>
                    </strong>
                  </div>
                  <span><strong>{{ttotal}}</strong></span>
                </li>
              </ul>
  
              <button type="button" class="btn btn-primary btn-lg btn-block">
                Go to checkout
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section> 
{% endblock %}

templates/cart2.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

this is the cart page. proceed to review your items and place the order

{% endblock %}
{% block title %}
      Cart -ABC Company PVT LTD
{% endblock %}
{% block content %}

{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shoppin cart is Empty
        </h1>
        <br>
        <p class="text-center">
            Please click <a href={% url 'shop:allProdCat' %}>Here</a> to continue shopping.
        </p>

    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your shopping cart
        </h1>
        <br>

    </div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">
                    Your Items
                </th>

            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="{{ cart_item.product.get_url }}"><img height="100px;" src="{{cart_item.product.image.url}}" alt="" class="float-left rounded custom_image"></a>
                </td>
                <td class="text-left">
                    {{cart_item.product.name}}
                    <br>
                    SKU: {{cart_item.product.id}}
                    <br>
                    shipping fee:  ${{cart_item.product.shippingprice}}
                    <br>
                    price: $ {{cart_item.product.price}}
                    <br>
                    QTY : {{cart_item.quantity}} x $ {{cart_item}}

                </td>
                <td>
                   : $ {{cart_item.sub_total}}

                </td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <!-- <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-plus custom_icon"></i></a>
                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                    <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i></a> 
                -->
                <!-- <img src="{% static 'img/minus.png' %}" style="width: 20px;"> -->
                   <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><img src="{% static 'img/plus.png' %}" style="width: 15px;"></a>
                   <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><img src="{% static 'img/minus.png' %}" style="width: 15px;"></a>
                   <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><img src="{% static 'img/bin.png' %}" style="width: 15px;"></a>
                </td>
                {% else %}
                <td>
                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><img src="{% static 'img/minus.png' %}" style="width: 15px;"></a>
                    <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><img src="{% static 'img/bin.png' %}" style="width: 15px;"></a>
                   
                </td>

                {% endif %}
            </tr>
            {% endfor %}
            </tbody>

        </table>

    </div>
   <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
       <table class="table my_custom_table">
           <thead class="my_custom_thead">
           <tr>
               <th>
                  Checkout
               </th>
           </tr>

           </thead>
           <tbody>
           <td>
               Please review your shopping cart items before proceeding with the order payment.
           </td>
           <tr>
               <td class="text-left">

                   Your Total is : <strong>$ {{ total }}</strong>

               </td>
            
           </tr>
           </tbody>

       </table>
       <div class="mx_auto">
           <a href={% url 'shop:allProdCat' %} class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
           <br>
           <br>
           <br>

           <a class="btn btn-danger" href="">Pay Now</a>

       </div>

 {% endif %}
   </div>
</div>
</div>
{% endblock %}

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{category.description|truncatewords:155}}
    {% else %}
        Welocome to ABC store where you can buys different items...
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
        {{ category.name }} -ABC Store
    {% else %}
        See our New Collections -ABC Store
    {% endif %}
{% endblock %}

{% block content %}
{% if category %}
      <div>
            <div class="row my_row_class">
                <div class="mx-auto">
                <p><a href="{% url 'shop:allProdCat' %}">Our Product Collections</a> | <a href="{%  url 'shop:allProdCat' %}">Home</a> </p>

                </div>
            </div>
        </div>
    {% endif %}
<div class="mx_auto">
    {% if category %}
        <img  class="my_image" src="{{category.image.url}}" alt="{{category.name}}">
</div>
    <br>
<div>
        <h1 class="text-center my_title">{{category.name}}</h1>
        <p class="text-justify">{{category.description}}</p>
</div>

    {% else %}
<div>
        <img class="my_image my_image_padding" src="{% static 'img/baner.png' %}" alt="Our products" width="100%";>
</div>
<br>
<div>
    <h1 class="text-center my_title" >Our Products Collections</h1>
    <p class="text-justify">Loremplytext of the.tthhthhhhhdvdftyhthhy Lojtyrem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
</div>
    {% endif %}
<div class="container">
    <div class="row mx_auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9  col-sm-12 col-sm-12 col-md-4 xol-lg-4" >
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image " style="height:200px; width: auto;" src="{{product.image.url}}" alt="{{product.name}}"> </a>
                <div class="card-body " style="background-color:black ; text-align: center; color: aqua;">
                    <h4>{{product.name}}</h4>
                     <p>{{product.price}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx_auto" style=" height: 100px;">
       {% if products.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}"  class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div> 


{% endblock %}


templates/footer.html




<style>
    .footer {
       position: fixed;
       left: 0;
       bottom: 0;
       width: 100%;
       background-color: rgb(174, 174, 174);
       color: white;
       text-align: center;
    }
    </style>
    </head>
    <body>
  
    
    <div class="footer">
        <p class="text-center">&copy; BECARDIEZ  tech pvt ltd.All rights Reserved </p>
    </div>
    
    </body>
    </html> 

templates/header.html
{% load static %}


<header>
  <center>
    <a href="{% url 'shop:allProdCat' %}"><img  src="{% static 'img/logo.jpg' %}" alt="logimage" width="130px;" ></a>

  </center>
</header>



templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light " style="background-color: #d2c9ff">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link" href="{%  url 'shop:allProdCat' %}">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'shop:allProdCat' %}">All Productd</a></li>
              {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
                {% endfor %}

          </ul>
        </li>
       
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><img src="{% static 'img/shopping-cart.png' %}" style="width: 15px;">({{item_count}})</a>
        </li>
        
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><img src="{% static 'img/shopping-cart.png' %}" style="width: 15px;">({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search" ></i></button>
      </form>
    </div>
  </div>
</nav>

templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

    {{product.description|truncatewords:155}}

{% endblock %}

{% block title %}
    {% if category %}
        {{ product.name }} -ABC Store
    {% endif %}

{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
    <div class="mx-auto">
        <P> <a href="{%  url 'shop:allProdCat' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a>| {{product.name}}</P>
    </div>
</div>
<div class="container">
<br>

<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img height="200px;" src="{{product.image.url}}" alt="{{product.name}}">

        </div>
    </div>


        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
            <h1 class="my_prod_title">{{product.name}}</h1>
            <p>price:  ${{product.price}}</p>
            <P>Shipping Fee :  {{product.shippingprice}}</P>
            <p class="my_title"><b>Product details</b></p>

            <P class="text-justify my_prod_text">{{product.description}}</P>

            {% if product.stock <= 0 %}
            <p class="text_justify my_prod_text"><b>Out Of Stock</b></p>
            {% else %}
            <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
            
            {% endif %}

        </div>
    </div>
</div>
</div>
</div>
{% endblock %}